# Generated by Django 4.1 on 2022-08-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0002_product_alter_customer_pincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
