# Generated by Django 4.1 on 2022-08-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0022_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
