# Generated by Django 4.1 on 2022-08-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0023_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='regdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
